# Python numerics
Author = R. Patrick Xian  
Date = 08/2017
## 1. math

In [3]:
import math
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [22]:
try:
    del math
except:
    pass
import math as m
from math import sin, pi, radians

In [5]:
sin(pi/2)

1.0

In [18]:
help(radians)

Help on built-in function radians in module math:

radians(...)
    radians(x)
    
    Convert angle x from degrees to radians.



In [25]:
sin(radians(30))

0.49999999999999994

In [23]:
m.floor(2.5), m.ceil(2.5)

(2, 3)

In [55]:
m.isnan(m.nan), m.isinf(m.inf)

(True, True)

In [53]:
frac, intg = m.modf(2.519)
print('The integer is {0:0}, the fraction is {1:0.3f}'.format(intg, frac))

The integer is 2.0, the fraction is 0.519


In [77]:
a = [0.1, 0.1, 0.1, 0.3, 0.1, 0.1, 0.1, 0.1, 0.1, 0., 0.1, 0.1]
sum(a), m.fsum(a)

(1.3000000000000003, 1.3)

In [80]:
m.e, m.e == m.exp(1)

(2.718281828459045, True)

## 2. numpy

In [91]:
import numpy as np

In [116]:
arr = np.array([-0.1,9.0,300,4])
arr, type(arr)

(array([ -1.00000000e-01,   9.00000000e+00,   3.00000000e+02,
          4.00000000e+00]), numpy.ndarray)

In [117]:
arr_properties = list(prop for prop in dir(arr) if not prop.startswith('__'))
print(arr_properties)

['T', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view']


In [154]:
arr.shape

(4,)

In [156]:
arr2d = np.atleast_2d(arr)
arr2d.shape

(1, 4)

In [164]:
arr2d.squeeze().shape

(4,)

In [157]:
arr2d

array([[ -1.00000000e-01,   9.00000000e+00,   3.00000000e+02,
          4.00000000e+00]])

In [158]:
arr2d == arr

array([[ True,  True,  True,  True]], dtype=bool)

In [159]:
arr.mean()

78.224999999999994

In [161]:
intarr = arr.astype('int')
intarr

array([  0,   9, 300,   4])

In [163]:
np.tile(intarr, (3,1))

array([[  0,   9, 300,   4],
       [  0,   9, 300,   4],
       [  0,   9, 300,   4]])

In [142]:
arr1 = np.array([[1,9,3,12],[0,5,4,2],[19,8,10,7]])
arr1

array([[ 1,  9,  3, 12],
       [ 0,  5,  4,  2],
       [19,  8, 10,  7]])

In [143]:
arr1.shape

(3, 4)

In [144]:
arr1.size

12

In [145]:
arr1.ravel()

array([ 1,  9,  3, 12,  0,  5,  4,  2, 19,  8, 10,  7])

In [146]:
arr1.flatten()

array([ 1,  9,  3, 12,  0,  5,  4,  2, 19,  8, 10,  7])

In [147]:
arr1.sum(), arr1.prod()

(80, 0)

In [148]:
arr1.reshape((2,6))

array([[ 1,  9,  3, 12,  0,  5],
       [ 4,  2, 19,  8, 10,  7]])

In [149]:
arr1

array([[ 1,  9,  3, 12],
       [ 0,  5,  4,  2],
       [19,  8, 10,  7]])

In [151]:
arr1.T

array([[ 1,  0, 19],
       [ 9,  5,  8],
       [ 3,  4, 10],
       [12,  2,  7]])

In [150]:
arr1.swapaxes(0,1)

array([[ 1,  0, 19],
       [ 9,  5,  8],
       [ 3,  4, 10],
       [12,  2,  7]])

In [153]:
np.prod(arr1.T == arr1.swapaxes(0,1))

1

## 3. scipy

In [86]:
import scipy as sp

## 4. pandas

In [7]:
import pandas as pd

## 5. sympy

In [8]:
import sympy as sp