# Python numerics
Author = R. Patrick Xian  
Date = 08/2017
## 1. math

In [1]:
import math
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [2]:
try:
    del math
except:
    pass
import math as m
from math import sin, pi, radians

In [3]:
sin(pi/2)

1.0

In [4]:
help(radians)

Help on built-in function radians in module math:

radians(...)
    radians(x)
    
    Convert angle x from degrees to radians.



In [5]:
sin(radians(30))

0.49999999999999994

In [6]:
m.floor(2.5), m.ceil(2.5)

(2, 3)

In [7]:
m.isnan(m.nan), m.isinf(m.inf)

(True, True)

In [8]:
frac, intg = m.modf(2.519)
print('The integer is {0:0}, the fraction is {1:0.3f}'.format(intg, frac))

The integer is 2.0, the fraction is 0.519


In [9]:
a = [0.1, 0.1, 0.1, 0.3, 0.1, 0.1, 0.1, 0.1, 0.1, 0., 0.1, 0.1]
sum(a), m.fsum(a)

(1.3000000000000003, 1.3)

In [10]:
m.e, m.e == m.exp(1)

(2.718281828459045, True)

## 2. numpy

### 2.1 basic math
Read the list of functions [here](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html)

### 2.2 numpy arrays
#### 2.2.1 array operations

In [11]:
import numpy as np

In [12]:
arr = np.array([-0.1,9.0,300,4])
arr, type(arr)

(array([ -1.00000000e-01,   9.00000000e+00,   3.00000000e+02,
          4.00000000e+00]), numpy.ndarray)

In [13]:
arr_properties = list(prop for prop in dir(arr) if not prop.startswith('__'))
print(arr_properties)

['T', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view']


In [14]:
arr.shape

(4,)

In [15]:
arr2d = np.atleast_2d(arr)
arr2d.shape

(1, 4)

In [16]:
arr2d.squeeze().shape

(4,)

In [17]:
arr2d

array([[ -1.00000000e-01,   9.00000000e+00,   3.00000000e+02,
          4.00000000e+00]])

In [18]:
arr2d == arr

array([[ True,  True,  True,  True]], dtype=bool)

In [19]:
arr.mean()

78.224999999999994

In [20]:
intarr = arr.astype('int')
intarr

array([  0,   9, 300,   4])

In [21]:
np.tile(intarr, (3,1))

array([[  0,   9, 300,   4],
       [  0,   9, 300,   4],
       [  0,   9, 300,   4]])

In [22]:
arr1 = np.array([[1,9,3,12],[0,5,4,2],[19,8,10,7]])
arr1

array([[ 1,  9,  3, 12],
       [ 0,  5,  4,  2],
       [19,  8, 10,  7]])

In [23]:
arr1.shape

(3, 4)

In [24]:
arr1.size

12

In [25]:
arr1.ravel()

array([ 1,  9,  3, 12,  0,  5,  4,  2, 19,  8, 10,  7])

In [26]:
arr1.flatten()

array([ 1,  9,  3, 12,  0,  5,  4,  2, 19,  8, 10,  7])

In [27]:
arr1.sum(), arr1.prod()

(80, 0)

In [28]:
arr1.reshape((2,6))

array([[ 1,  9,  3, 12,  0,  5],
       [ 4,  2, 19,  8, 10,  7]])

In [29]:
arr1

array([[ 1,  9,  3, 12],
       [ 0,  5,  4,  2],
       [19,  8, 10,  7]])

In [30]:
arr1.T

array([[ 1,  0, 19],
       [ 9,  5,  8],
       [ 3,  4, 10],
       [12,  2,  7]])

In [31]:
arr1.swapaxes(0,1)

array([[ 1,  0, 19],
       [ 9,  5,  8],
       [ 3,  4, 10],
       [12,  2,  7]])

In [32]:
np.prod(arr1.T == arr1.swapaxes(0,1))

1

#### 2.2.2 array indexing

In [39]:
arr1

array([[ 1,  9,  3, 12],
       [ 0,  5,  4,  2],
       [19,  8, 10,  7]])

In [38]:
arr1[0,:]

array([ 1,  9,  3, 12])

In [40]:
arr1[0,1]

9

In [44]:
arr1[1:10:2]

array([[0, 5, 4, 2]])

In [47]:
arr1[arr1 > 5]

array([ 9, 12, 19,  8, 10,  7])

In [48]:
# Output the array indices
np.argwhere(arr1 > 5)

array([[0, 1],
       [0, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3]], dtype=int64)

In [54]:
np.where(arr1 > 5)

(array([0, 0, 2, 2, 2, 2], dtype=int64),
 array([1, 3, 0, 1, 2, 3], dtype=int64))

In [55]:
arr1[_]

array([ 9, 12, 19,  8, 10,  7])

#### 2.2.3 array broadcasting

### 2.3 linear algebra (numpy.linalg)
See the list of functions [here](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html)

In [34]:
from numpy.linalg import norm

In [35]:
norm([3,4])

5.0

### 2.4 array iterator

### 2.5 masked array (numpy.ma)

## 3. scipy

In [36]:
import scipy as sp

## 4. pandas

In [ ]:
import pandas as pd

In [ ]:
d = {'Elements':['Hydrogen', 'Oxygen', 'Sulfur', 'Tungsten', 'Europium'],\
     'Z':[0,1,2,3,4],\
     'Weight':[111,222,333,444,555]}
df = pd.DataFrame.from_dict(d)
df

### 4.1 Read from [table of elements](http://images-of-elements.com/element-properties.php)

## 5. sympy

In [57]:
import sympy as sym