# Python numerics
Author = R. Patrick Xian  
Date = 08/2017
## 1. math -- built-in math

In [1]:
import math
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [2]:
try:
    del math
except:
    pass
import math as m
from math import sin, pi, radians

In [3]:
sin(pi/2)

1.0

In [4]:
help(radians)

Help on built-in function radians in module math:

radians(...)
    radians(x)
    
    Convert angle x from degrees to radians.



In [5]:
sin(radians(30))

0.49999999999999994

In [6]:
m.floor(2.5), m.ceil(2.5)

(2, 3)

In [7]:
m.isnan(m.nan), m.isinf(m.inf)

(True, True)

In [8]:
frac, intg = m.modf(2.519)
print('The integer is {0:0}, the fraction is {1:0.3f}'.format(intg, frac))

The integer is 2.0, the fraction is 0.519


In [9]:
a = [0.1, 0.1, 0.1, 0.3, 0.1, 0.1, 0.1, 0.1, 0.1, 0., 0.1, 0.1]
sum(a), m.fsum(a)

(1.3000000000000003, 1.3)

In [10]:
m.e, m.e == m.exp(1)

(2.718281828459045, True)

## 2. numpy -- numeric operations

### 2.1 basic math
Read the list of functions [here](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html)

### 2.2 numpy arrays
#### 2.2.1 array operations

In [11]:
import numpy as np

In [12]:
arr = np.array([-0.1,9.0,300,4])
arr, type(arr)

(array([ -1.00000000e-01,   9.00000000e+00,   3.00000000e+02,
          4.00000000e+00]), numpy.ndarray)

In [13]:
arr_properties = list(prop for prop in dir(arr) if not prop.startswith('__'))
print(arr_properties)

['T', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view']


In [14]:
arr.shape

(4,)

In [15]:
arr2d = np.atleast_2d(arr)
arr2d.shape

(1, 4)

In [16]:
arr2d.squeeze().shape

(4,)

In [17]:
arr2d

array([[ -1.00000000e-01,   9.00000000e+00,   3.00000000e+02,
          4.00000000e+00]])

In [18]:
arr2d == arr

array([[ True,  True,  True,  True]], dtype=bool)

In [19]:
arr.mean()

78.224999999999994

In [20]:
intarr = arr.astype('int')
intarr

array([  0,   9, 300,   4])

In [22]:
arr1 = np.array([[1,9,3,12],[0,5,4,2],[19,8,10,7]])
arr1

array([[ 1,  9,  3, 12],
       [ 0,  5,  4,  2],
       [19,  8, 10,  7]])

In [23]:
arr1.shape

(3, 4)

In [24]:
arr1.size

12

In [25]:
arr1.ravel()

array([ 1,  9,  3, 12,  0,  5,  4,  2, 19,  8, 10,  7])

In [26]:
arr1.flatten()

array([ 1,  9,  3, 12,  0,  5,  4,  2, 19,  8, 10,  7])

In [27]:
arr1.sum(), arr1.prod()

(80, 0)

In [28]:
arr1.reshape((2,6))

array([[ 1,  9,  3, 12,  0,  5],
       [ 4,  2, 19,  8, 10,  7]])

In [29]:
arr1

array([[ 1,  9,  3, 12],
       [ 0,  5,  4,  2],
       [19,  8, 10,  7]])

In [30]:
arr1.T

array([[ 1,  0, 19],
       [ 9,  5,  8],
       [ 3,  4, 10],
       [12,  2,  7]])

In [31]:
arr1.swapaxes(0,1)

array([[ 1,  0, 19],
       [ 9,  5,  8],
       [ 3,  4, 10],
       [12,  2,  7]])

In [32]:
np.prod(arr1.T == arr1.swapaxes(0,1))

1

#### 2.2.2 [array indexing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)

In [33]:
arr1

array([[ 1,  9,  3, 12],
       [ 0,  5,  4,  2],
       [19,  8, 10,  7]])

In [34]:
arr1[0,:]

array([ 1,  9,  3, 12])

In [35]:
arr1[0,1]

9

In [36]:
arr1[1:10:2]

array([[0, 5, 4, 2]])

In [37]:
arr1[arr1 > 5]

array([ 9, 12, 19,  8, 10,  7])

In [38]:
# Output the array indices
np.argwhere(arr1 > 5)

array([[0, 1],
       [0, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3]], dtype=int64)

In [39]:
np.where(arr1 > 5)

(array([0, 0, 2, 2, 2, 2], dtype=int64),
 array([1, 3, 0, 1, 2, 3], dtype=int64))

In [40]:
arr1[_]

array([ 9, 12, 19,  8, 10,  7])

#### 2.2.3 [array broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)

In [68]:
arr = np.array([1,2,3,4])

In [67]:
stacked_arr = np.tile(arr, (3,1))
stacked_arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [53]:
np.broadcast_to(arr, (2,arr.size))

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [69]:
stacked_arr + arr

array([[2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8]])

In [72]:
stacked_arr * arr

array([[ 1,  4,  9, 16],
       [ 1,  4,  9, 16],
       [ 1,  4,  9, 16]])

In [70]:
stacked_arr + arr[:-1]

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [75]:
stacked_arr.T

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [71]:
stacked_arr.T + arr[:-1]

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

### 2.3 linear algebra (numpy.linalg)
See the list of functions [here](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html)

In [58]:
from numpy.linalg import norm, multi_dot
import numpy.linalg as nplin

In [43]:
norm([3,4])

5.0

In [61]:
A = np.random.random((10000, 100))
B = np.random.random((100, 1000))
C = np.random.random((1000, 5))
D = np.random.random((5, 333))

In [64]:
%timeit A.dot(B).dot(C).dot(D)

10 loops, best of 3: 80.9 ms per loop


In [65]:
%timeit multi_dot([A, B, C, D])

100 loops, best of 3: 13.4 ms per loop


In [78]:
np.prod(np.isclose(A.dot(B).dot(C).dot(D), multi_dot([A, B, C, D]), atol=1e-8))

1

In [56]:
print(dir(nplin))

['LinAlgError', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_numpy_tester', '_umath_linalg', 'absolute_import', 'bench', 'cholesky', 'cond', 'det', 'division', 'eig', 'eigh', 'eigvals', 'eigvalsh', 'info', 'inv', 'lapack_lite', 'linalg', 'lstsq', 'matrix_power', 'matrix_rank', 'multi_dot', 'norm', 'pinv', 'print_function', 'qr', 'slogdet', 'solve', 'svd', 'tensorinv', 'tensorsolve', 'test']


### 2.4 array iterator (numpy.nditer)
[Documentation](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.nditer.html#numpy.nditer) and [examples](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.nditer.html)

### 2.5 masked array (numpy.ma)

In [97]:
import numpy.ma as nma

## 3. [scipy](https://docs.scipy.org/doc/scipy-0.19.1/reference/) -- scientific computing

In [44]:
import scipy as sp

In [92]:
import pkgutil
for _, modname, _ in pkgutil.iter_modules(sp.__path__):
    if not modname.startswith('_'):
        print("scipy.{}".format(modname))

scipy.cluster
scipy.constants
scipy.fftpack
scipy.integrate
scipy.interpolate
scipy.io
scipy.linalg
scipy.misc
scipy.ndimage
scipy.odr
scipy.optimize
scipy.setup
scipy.signal
scipy.sparse
scipy.spatial
scipy.special
scipy.stats
scipy.version


In [94]:
import scipy.constants as const
print(dir(const))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'C2F', 'C2K', 'ConstantWarning', 'F2C', 'F2K', 'G', 'Julian_year', 'K2C', 'K2F', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Tester', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_obsolete_constants', 'absolute_import', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'division', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'g

In [95]:
import scipy.fftpack as fft
print(dir(fft))

['Tester', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_fftpack', 'absolute_import', 'basic', 'bench', 'cc_diff', 'convolve', 'cs_diff', 'dct', 'diff', 'division', 'dst', 'fft', 'fft2', 'fftfreq', 'fftn', 'fftpack_version', 'fftshift', 'helper', 'hilbert', 'idct', 'idst', 'ifft', 'ifft2', 'ifftn', 'ifftshift', 'ihilbert', 'irfft', 'itilbert', 'next_fast_len', 'print_function', 'pseudo_diffs', 'realtransforms', 'rfft', 'rfftfreq', 'sc_diff', 'shift', 'ss_diff', 'test', 'tilbert']


In [96]:
import scipy.optimize as opt
print(dir(opt))

['LbfgsInvHessProduct', 'OptimizeResult', 'OptimizeWarning', 'Tester', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_basinhopping', '_cobyla', '_differentialevolution', '_group_columns', '_hungarian', '_lbfgsb', '_linprog', '_lsq', '_minimize', '_minpack', '_nnls', '_numdiff', '_root', '_slsqp', '_spectral', '_trustregion', '_trustregion_dogleg', '_trustregion_ncg', '_zeros', 'absolute_import', 'anderson', 'approx_fprime', 'basinhopping', 'bench', 'bisect', 'bracket', 'brent', 'brenth', 'brentq', 'broyden1', 'broyden2', 'brute', 'check_grad', 'cobyla', 'curve_fit', 'diagbroyden', 'differential_evolution', 'division', 'excitingmixing', 'fixed_point', 'fmin', 'fmin_bfgs', 'fmin_cg', 'fmin_cobyla', 'fmin_l_bfgs_b', 'fmin_ncg', 'fmin_powell', 'fmin_slsqp', 'fmin_tnc', 'fminbound', 'fsolve', 'golden', 'lbfgsb', 'least_squares', 'leastsq', 'line_search', 'linear_sum_assignment', 'linearmixing', 'linesearch',

#### Test minimization using the [Rosenbrock function](https://en.wikipedia.org/wiki/Rosenbrock_function)

## 4. pandas -- time series, panel data

In [45]:
import pandas as pd

In [46]:
d = {'Elements':['Hydrogen', 'Oxygen', 'Sulfur', 'Tungsten', 'Europium'],\
     'Z':[0,1,2,3,4],\
     'Weight':[111,222,333,444,555]}
df = pd.DataFrame.from_dict(d)
df

Elements  Weight  Z
0  Hydrogen     111  0
1    Oxygen     222  1
2    Sulfur     333  2
3  Tungsten     444  3
4  Europium     555  4

### 4.1 read from [table of elements](http://images-of-elements.com/element-properties.php)

### 4.2 tabular operations

### 4.3 method chaining

## 5. [sympy](http://docs.sympy.org/latest/index.html) -- symbolic computation

In [47]:
import sympy as sym

In [80]:
x = sym.symbols('x')
expr = 0.2*x + 1
fx = sym.lambdify(x, expr, 'numpy')
fx(5)

2.0

In [82]:
sym.integrate(expr, x)

0.1*x**2 + 1.0*x

In [83]:
sym.simplify(_)

x*(0.1*x + 1.0)